global.leftKey = keyboard_check(ord("A"))
global.rightKey = keyboard_check(ord("D"))
global.upKey = keyboard_check(ord("W"))
global.downKey = keyboard_check(ord("S"))
global.sprintKey = keyboard_check(vk_shift)

global.shootKey = mouse_check_button(mb_left)
global.shootPressed = mouse_check_button_pressed(mb_left)
global.reloadKey = keyboard_check_pressed(ord("R"))
global.swapKey = mouse_check_button_pressed(mb_right)
global.spaceKey = keyboard_check(vk_space)

global.num1Key = keyboard_check(ord("1"))
global.num2Key = keyboard_check(ord("2"))
global.num3Key = keyboard_check(ord("3"))
global.num4Key = keyboard_check(ord("4"))
